name: PyPI Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/invenio-subjects-nasa
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pip install twine
        pip freeze
    - name: Run package build
      run: |
        python setup.py sdist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
