# -*- coding: utf-8 -*-
#
# Copyright (C) 2022-2025 KTH Royal Institute of Technology.
#
# invenio-subjects-nasa is free software, you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file details.

name: PyPI Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/invenio-subjects-nasa
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Run package build
      run: |
        python -m build
    - name: Check package
      run: |
        twine check dist/*
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
